HomeworkPublish/urls.py
from django.urls import path
from . import views

app_name = 'HomeworkPublish'

urlpatterns = [
    path('Homework_list/', views.Homework_list, name='Homework_list'),
    path('Homework_Publish/<int:id>',views.Homework_Publish,name='Homework_Publish'),
    path('Homework_delete/<int:id>/',views.Homework_delete,name='Homework_delete'),
]

Login/urls.py
from django.urls import path
from . import views

app_name = 'Login'
urlpatterns = [
    path('home/', views.PAGE, name = 'PAGE'),
    #path('login/', views.logIn, name = 'logIn'),
    path('logout/', views.logOut, name = 'logOut'),
    path('register/', views.Register, name = 'Register'),
    path('addcourse/', views.addcourse, name = 'addcourse'),
    path('joincourse/', views.joincourse, name = 'joincourse'),
    path('coursedetail/<int:id>',views.coursedetail, name = 'coursedetail'),
    path('homeworkdetail/<int:id>',views.homeworkdetail, name = 'homeworkdetail'),
    path('makecomments/', views.makecomments, name = 'makecomments'),
    path('coursedelete/<int:id>',views.coursedelete, name = 'coursedelete'),
    path('courserejust/<int:id>',views.courserejust, name = 'courserejust'),
    path('addassistant/<int:id>',views.addassistant, name = 'addassistant'),
    path('upload/<int:id>/',views.homeworkdetail,name = 'upload'),
    path('user-center/', views.usercenter, name = 'usercenter'),
    path('persondetail/',views.persondetail,name='persondetail'),
    path('user-center/edit-profile', views.editprofile, name = 'editprofile'),
    path('user-center/change-password', views.changepassword, name = 'changepassword'),
    path('checkcomments/<int:id>', views.checkcomments, name = 'checkcomments'),
]

projectTen/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf.urls.static import static
import projectTen.settings
import notifications.urls
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Login.urls',namespace='Login')),
    path('',include('HomeworkPublish.urls',namespace='HomeworkPublish')),
    path('captcha/', include('captcha.urls')),
    path('comment/', include('comment.urls', namespace='comment')),
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
    path('notice/', include('notice.urls', namespace='notice')),
    
]+ static (projectTen.settings.MEDIA_URL, document_root=projectTen.settings.MEDIA_ROOT)

HomeworkPublish/models.py
from django.db import models

from django.contrib.auth.models import User

from django.utils import timezone

# 作业模型，包含各项内容如下
class Homework(models.Model):
    #subject = models.ForeignKey(user, on_delete=models.CASCADE)
    Homework_title =models.TextField()
    Homework_text =models.TextField()
    courseNum = models.IntegerField()
    Pub_time = models.DateTimeField(default=timezone.now)
    deadline_date = models.TextField()
    deadline_time = models.TextField(default='23:59')

    class Meta:
        ordering = ('-Pub_time',)
    
    def __str__(self):
        return self.Homework_title
    
    def was_created_recently(self):
        # 若评论是"最近"发表的，则返回 True
        diff = timezone.now() - self.Pub_time
        if diff.days <= 0 and diff.seconds < 60:
            return True
        else:
            return False

HomeworkPublish/forms.py
from django import forms
from .models import Homework

#作业发布的提交表单
class HomeworkFrom(forms.ModelForm):
    class Meta:
        model = Homework
        fields = ('Homework_text','deadline_date','deadline_time')

HomeworkPublish/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .forms import HomeworkFrom
from django.contrib.auth.models import User
from .models import Homework 
from notifications.signals import notify
from Login.models import stucourse
from Login.models import course
from django.contrib import messages
# Create your views here.

#展示作业列表
def Homework_list(request):
    homework = Homework.objects.all()
    context = {'homework':homework}
    return render(request, 'HomeworkPublish/list.html',context)

#作业发布
def Homework_Publish(request,id):
    homework = Homework()
    if request.method == "POST":
        Homework_Publish_form = HomeworkFrom(data=request.POST)
        if Homework_Publish_form.is_valid():
            homework.courseNum = id
            homework.Homework_title = request.POST['Homework_title']
            homework.Homework_text = request.POST['Homework_text']
            homework.deadline_date = request.POST['deadline_date']
            homework.deadline_time = request.POST['deadline_time']
            students = stucourse.objects.filter(thecourse_id = id)
            c = course.objects.get(id=id)
            homework.save()
            for student in students:
                stu = User.objects.get(username = student.studentName)
                notify.send(
                    request.user,
                    recipient=stu,
                    verb='创建了作业',
                    target=c,
                    action_object=homework,
                    
                ) 
            messages.info(request,"发布成功")
            #return HttpResponse("已发布，请返回刷新页面")
        else:
            messages.error(request,"作业内容有误，请重新填写")
            #return HttpResponse("作业内容有误，请重新填写。")
    return render(request,'HomeworkPublish/Publish.html',{'hw':homework})

#作业删除
def Homework_delete(request,id):
    homework = Homework.objects.get(id=id)
    ID=homework.courseNum
    homework.delete()
    mycourse = course.objects.get(id=ID)
    sc = stucourse.objects.filter( thecourse_id = ID)
    hw=Homework.objects.filter(courseNum = ID)
    context = {'mycourse':mycourse,'sc':sc,'hw':hw}
    messages.info(request,"已删除此作业")
    return render(request,'Login/coursedetail.html',context)

templates/HomeworkPublish/Publish.html
<!-- extends表明此页面继承自 baseReg.html 文件 -->
{% extends "baseHome.html" %}
{% load staticfiles %}

<!-- 写入 baseHome.html 中定义的 title -->
{% block title %}
    作业发布
{% endblock title %}

<!--加入滚动条-->
<div style="position:absolute; height:400px; overflow:auto">
</div>

<!-- 写入 baseHome.html 中定义的 content -->
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <form method="POST" action="">
                {% csrf_token %}
                <!--作业内容-->
                <div class="form-group col-md-4">
                    <label for="Homework_title">作业标题:</label>
                    <br/>
                    <input type="text" class="form-control" id="Homework_title" name="Homework_title">
                </div>
                <div class="form-group col-md-12">
                    <label for="Homework_text">作业内容:</label>
                    <br/>
                    <textarea type="text" class="form-control" id="Homework_text" name="Homework_text" rows="10"></textarea>
                </div>
                
                <div class="form-group col-md-4">
                    <label for="deadline_date">截止日期:</label>
                    <br/>
                    <input type="date" class="form-control" id="deadline_date" name="deadline_date">
                </div>
                
                <div class="form-group col-md-4">
                    <label for="deadline_time">截止时间:</label>
                    <br/>
                    <input type="time" class="form-control" id="deadline_time" name="deadline_time">
                </div>

                <!--提交按钮-->
                <div class="form-group col-md-4">
                    <button type="submit" class="btn btn-primary">完成</button>
                </div>
                {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                    {% if message.level == DEFAULT_MESSAGE_LEVELS.INFO %}
                        <script type="text/javascript">
                            function feedback() {
                                layer.open({
                                    title: "来自本网页的提示",
                                    content: "发布成功",
                                    end : function() {
                                        location.href='{% url "Login:coursedetail" hw.courseNum %}'
                                    },
                    
                                })
                            }
                            window.onload = feedback;
                        </script>
                    {% endif %}
                    {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                        <script type="text/javascript">
                            function feedback() {
                                layer.open({
                                    title: "来自本网页的提示",
                                    content: "作业内容有误，请重新填写",
                                    end : function() {
                                        location.href=document.referrer
                                    },
                    
                                })
                            }
                            window.onload = feedback;
                        </script>
                    {% endif %}
                    {% endfor %} 
                </ul>
                {% endif %}
            </form>
        </div>
    </div>
</div>      
{% endblock content %}

templates/HomeworkPublish/list.html
作业列表：
<table>
    <tr>
        <td>课程编号</td>
        <td>作业内容</td>
        <td>发布时间</td>
        <td>截止时间</td>
    </tr>
    {% for Homework in homework %}
    <tr>
        <td>{{ Homework.courseNum }}</td>
        <td>{{ Homework.Homework_text}}</td>
        <td>{{ Homework.Pub_time }}</td>
        <td>{{ Homework.deadline_date}} {{ Homework.deadline_time}}</td>
    </tr>
    {% endfor %}
</table>

<!--加入滚动条-->
<div style="position:absolute; height:400px; overflow:auto">
</div>