HomeworkPublish/urls.py
from django.urls import path
from . import views

app_name = 'HomeworkPublish'

urlpatterns = [
    path('Homework_list/', views.Homework_list, name='Homework_list'),
    path('Homework_Publish/<int:id>',views.Homework_Publish,name='Homework_Publish'),
    path('Homework_delete/<int:id>/',views.Homework_delete,name='Homework_delete'),
]

Login/urls.py
from django.urls import path
from . import views

app_name = 'Login'
urlpatterns = [
    path('home/', views.PAGE, name = 'PAGE'),
    #path('login/', views.logIn, name = 'logIn'),
    path('logout/', views.logOut, name = 'logOut'),
    path('register/', views.Register, name = 'Register'),
    path('addcourse/', views.addcourse, name = 'addcourse'),
    path('joincourse/', views.joincourse, name = 'joincourse'),
    path('coursedetail/<int:id>',views.coursedetail, name = 'coursedetail'),
    path('homeworkdetail/<int:id>',views.homeworkdetail, name = 'homeworkdetail'),
    path('makecomments/', views.makecomments, name = 'makecomments'),
    path('coursedelete/<int:id>',views.coursedelete, name = 'coursedelete'),
    path('courserejust/<int:id>',views.courserejust, name = 'courserejust'),
    path('addassistant/<int:id>',views.addassistant, name = 'addassistant'),
    path('upload/<int:id>/',views.homeworkdetail,name = 'upload'),
    path('user-center/', views.usercenter, name = 'usercenter'),
    path('persondetail/',views.persondetail,name='persondetail'),
    path('user-center/edit-profile', views.editprofile, name = 'editprofile'),
    path('user-center/change-password', views.changepassword, name = 'changepassword'),
    path('checkcomments/<int:id>', views.checkcomments, name = 'checkcomments'),
]

projectTen/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf.urls.static import static
import projectTen.settings
import notifications.urls
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Login.urls',namespace='Login')),
    path('',include('HomeworkPublish.urls',namespace='HomeworkPublish')),
    path('captcha/', include('captcha.urls')),
    path('comment/', include('comment.urls', namespace='comment')),
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
    path('notice/', include('notice.urls', namespace='notice')),
    
]+ static (projectTen.settings.MEDIA_URL, document_root=projectTen.settings.MEDIA_ROOT)

upload/urls.py
from django.urls import path
from . import views

# 正在部署的应用的名称
app_name = "upload"

urlpatterns=[
    path('',views.register),
    path('filelist/',views.display,name="filelist"),
]

Login/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class normaluserform(models.Model):
    USER = models.OneToOneField(User, on_delete=models.CASCADE)
    nickname = models.CharField(blank=True,max_length=50)
    Identity = models.CharField(max_length=2)
    
    class Meta:
        verbose_name_plural = "normaluserform"
    
class course(models.Model):
    teacherName = models.CharField(max_length=10)
    courseNum = models.CharField(max_length=10)
    courseName = models.CharField(max_length=10)
    def __str__(self):
        return self.courseName
    def returncourseNum(self):
        return self.courseNum
class stucourse(models.Model):
    studentName = models.CharField(max_length=10)
    thecourse = models.ForeignKey('course',on_delete=models.CASCADE)

class asscourse(models.Model):
    assistantName = models.CharField(max_length=10)
    thecourse = models.ForeignKey('course',on_delete=models.CASCADE)

upload/models.py
from django.db import models
from HomeworkPublish.models import Homework
# Create your models here.

# Create your models here.
class userfile(models.Model):
    username = models.CharField(max_length = 30)
    homework = models.ForeignKey(
        Homework,
        on_delete=models.CASCADE,
    )
    headImg = models.FileField(upload_to= './files/')
    #所以是用upload_to来指定文件存放的前缀路径
    def __str__(self):
        return self.homework.Homework_Text
    
    def returnhomeworkcourseNum(self):
        return self.homework.courseNum

Login/forms.py
from django.contrib.auth.forms import UserCreationForm,UserChangeForm,AuthenticationForm
from django.contrib.auth.models import User
from django import forms
from captcha.fields import CaptchaField

class customizedloginForm(AuthenticationForm):
    VerificationCode = CaptchaField()

class customizededitForm(UserChangeForm):
    nickname = forms.CharField(required=False,max_length=50)
    Identity = forms.CharField(max_length=100)

    class Meta:
        model = User
        fields = ('username','password','email','nickname','Identity')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].error_messages = {'unique':'该用户名已存在！' , 'invalid':'该用户名格式不符合要求！'}


class customizedregisterForm(UserCreationForm):
    nickname = forms.CharField(required=False,max_length=50)
    Identity = forms.CharField(max_length=100)
    VerificationCode = CaptchaField()

    class Meta:
        model = User
        fields = ('username','password1','password2','email','nickname','Identity')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].error_messages = {'unique':'该用户名已存在！' , 'invalid':'该用户名格式不符合要求！'}

Login/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.forms import UserCreationForm,UserChangeForm, PasswordChangeForm
from django.http import HttpResponse
from django.db.models import Q
from django.contrib.auth.models import User
from notifications.signals import notify
from django.contrib import messages
from .forms import customizedregisterForm,customizededitForm,customizedloginForm
from .models import normaluserform
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from HomeworkPublish.models import Homework
from upload.models import userfile
from comment.models import Comment
from .models import course
from .models import stucourse
from .models import asscourse
import markdown
import time,datetime

#主页，包含登录模块，以及传各种参数
def PAGE(request):
    if request.user.is_authenticated:
        mycourse=course.objects.filter(teacherName = request.user.username)
        sc = stucourse.objects.filter(studentName = request.user.username)
        ac = asscourse.objects.filter(assistantName = request.user.username)
        hw=Homework.objects.all()
        uf=userfile.objects.all()
        us=normaluserform.objects.all()
        nowu=request.user
        request.session['role']=nowu.normaluserform.Identity
        context={'hw':hw,'uf':uf,'us':us,'mycourse':mycourse,'sc':sc,'ac':ac}
        return render(request, 'Login/home.html',context)
    else:
        if request.method == 'POST':
            loginform = customizedloginForm(data= request.POST)
            if loginform.is_valid():

                USER = authenticate(request,username=loginform.cleaned_data['username'] ,password=loginform.cleaned_data['password'] )

                login(request,USER)
                return redirect('Login:PAGE')
        else:
            loginform = customizedloginForm()

    Content = {'loginform':loginform, 'USER':request.user}
    return render(request, 'Login/home.html',Content)





#登出模块
def logOut(request):
    try:
        del request.session['role']
    except KeyError:
        pass
    logout(request)
    return redirect('Login:PAGE')

#注册
def Register(require):
    if require.method == 'POST':
        registerform = customizedregisterForm(require.POST)
        if registerform.is_valid():
            registerform.save()
            USER = authenticate(username=registerform.cleaned_data['username'] ,password=registerform.cleaned_data['password1'] )
            USER.email = registerform.cleaned_data['email']
            normaluserform(USER=USER,nickname=registerform.cleaned_data['nickname'],Identity=registerform.cleaned_data['Identity']).save()
            login(require,USER)
            return redirect('Login:PAGE')
    else:
        registerform = customizedregisterForm()

    Content = {'registerform':registerform}
    return render(require, 'Login/register.html', Content)

#用户中心（需登录）
@login_required(login_url='Login:logIn')
def usercenter(require):
    Content = {'USER': require.user}
    return render(require, 'Login/user-center.html', Content)
#编辑个人信息（需登录）
@login_required(login_url='Login:logIn')
def editprofile(require):
    if require.method == 'POST':
        editprofileform = customizededitForm(require.POST,instance = require.user)
        if editprofileform.is_valid():
            editprofileform.save()
            require.user.normaluserform.nickname = editprofileform.cleaned_data['nickname']
            require.user.normaluserform.Identity = editprofileform.cleaned_data['Identity']
            require.user.normaluserform.save()
            return redirect('Login:usercenter')
    else:
        editprofileform = customizededitForm(instance = require.user)

    Content = {'editprofileform':editprofileform, 'USER':require.user}
    return render(require, 'Login/edit-profile.html', Content)


#修改密码（需登录）
@login_required(login_url='Login:logIn')
def changepassword(require):
    if require.method == 'POST':
        changepasswordForm = PasswordChangeForm(data= require.POST,user = require.user)
        if changepasswordForm.is_valid():
            changepasswordForm.save()
            return redirect('Login:PAGE')
    else:
        changepasswordForm = PasswordChangeForm(user = require.user)

    Content = {'changepasswordForm':changepasswordForm, 'USER':require.user}
    return render(require, 'Login/change-password.html', Content)

# 作业详情与提交
def homeworkdetail(request,id):
    homework = Homework.objects.get(id=id)
    #添加markdown语法
    #nowtime = timezone.now()
    homework.Homework_text = markdown.markdown(homework.Homework_text,
        extensions=[
        # 包含 缩写、表格等常用扩展
        'markdown.extensions.extra',
        # 语法高亮扩展
        'markdown.extensions.codehilite',
        ])
    #判断时间
    nowtime = datetime.datetime.now()
    date_str = homework.deadline_date
    time_str = homework.deadline_time
    date_fmt = '%Y-%m-%d'
    time_fmt = '%H:%M'
    date_tuple = time.strptime(date_str, date_fmt)
    year, month, day = date_tuple[:3]
    time_tuple = time.strptime(time_str,time_fmt)
    hour, minute = date_tuple[3:5]
    deadline = datetime.datetime(year, month, day, hour, minute)
    #上交作业
    uf=userfile()
    if request.method == "POST":
        uf.username = request.user.username
        uf.homework = homework
        uf.headImg = request.FILES.get('tttt',None)
        uf.save()
        messages.info(request,"上传成功")
        #return HttpResponse('upload ok!')
    #判断提交状态;
    flag=False
    if userfile.objects.filter(homework_id=id,username=request.user.username):
        flag=True
    context = {'homework':homework,'nowtime':nowtime,'deadline':deadline,'uf':uf,'flag':flag}
    return render(request,'Login/homeworkdetail.html',context)

#增设课程（需要老师的权限）
def addcourse(request):
    Nowcourse = course()
    if request.method == "POST":
        Nowcourse.teacherName = request.user.username
        Nowcourse.courseNum = request.POST['courseNum']
        Nowcourse.courseName = request.POST['courseName']
        Nowcourse.save()
        messages.info(request,"添加成功")
        #return HttpResponse('添加成功')
    return render(request,'Login/addcourse.html',{'Nowcourse':Nowcourse})

#加入课程（需要学生的权限）
def joincourse(request):
    search = request.GET.get('search')
    if search:
        target = course.objects.filter(
            Q(courseNum__icontains=search)
        )
    else:
        search=''
        target =  course.objects.all()
    join = request.GET.get('join')
    if join:
        courselist = stucourse.objects.filter(studentName=request.user.username)
        courseID = request.GET.get('ID')
        flag = False
        if stucourse.objects.filter(studentName=request.user.username,thecourse_id=courseID):
            flag = True
        if flag == False:
            joinCourse = stucourse()
            joinCourse.studentName = request.user.username
            joinCourse.thecourse = course.objects.get(id=courseID)
            joinCourse.save()
            messages.info(request,"加入成功")
        else:
            messages.error(request,"您已添加过此课程")
    context = {'search':search,'target':target}
    return render(request,"Login/joincourse.html",context)

#展示课程细节
def coursedetail(request,id):
    mycourse=course.objects.get(id = id)
    sc = stucourse.objects.filter( thecourse_id = id)
    hw=Homework.objects.filter(courseNum = id)
    context = {'mycourse':mycourse,'sc':sc,'hw':hw}
    return render(request,'Login/coursedetail.html',context)

#删除课程(老师)
def coursedelete(request,id):
    target = course.objects.get(id=id)
    target.delete()
    messages.info(request,"已删除此课程")
    return redirect('Login:PAGE')
#退出课程（学生）
def courserejust(request,id):
    target = stucourse.objects.filter(thecourse_id=id)
    for item in target: 
        item.delete()
    messages.error(request,"已退出此课程")
    return redirect('Login:PAGE')

#为某门课添加助教（需要老师的权限）
def addassistant(request,id):
    assistant = asscourse()
    Course = course.objects.get(id=id)
    if request.method == "POST":
        assistant.assistantName = request.POST['assistantName']
        assistant.thecourse = Course
        assistant.save()
        messages.info(request,"添加成功")
        #return HttpResponse('添加成功')
    return render(request,'Login/addassistant.html',{'Course':Course})


#展示需要评论的列表
def makecomments(request):
    hwID = request.GET.get('hwID')
    course = Homework.objects.get(id=hwID)
    studentlist = stucourse.objects.filter(thecourse_id=course.courseNum)
    if hwID:
        homeworklist = userfile.objects.filter(homework_id=hwID)
        uncomplete = []
        for name1 in studentlist:
            for name2 in homeworklist:
                if name1.studentName == name2.username:
                    pass
                else:
                    uncomplete.append(name1)
        
        context = {'homeworklist':homeworklist,'uncomplete':uncomplete}
    else:
        context = {}
    return render(request,'Login/makecomment.html',context)

#某一个人的信息
def persondetail(request):
    user = request.GET['user']
    detail = User.objects.get(username = user )
    return render(request,'Login/persondetail.html',{'detail':detail})

#查看分数（需要学生的权限）
def checkcomments(request,id):
    homeworks = Homework.objects.filter(courseNum=id)
    comments = []
    for homework in homeworks:
        uploads = userfile.objects.filter(homework_id = homework.id)
        for upload in uploads:
            if upload.username == request.user.username:
                cm = Comment.objects.get(userfile_id = upload.id)
                comments.append(cm)
    context = {'comments':comments}
    return render(request,'Login/checkcomments.html',context)
                

upload/views.py
from django.shortcuts import render,render_to_response
from django.http import HttpResponse
from .models import userfile

def register(request):
    uf=userfile()
    if request.method == "POST":
        uf.username = request.POST['name']
        uf.username = request.POSt['courseNum']
        uf.headImg = request.FILES.get('tttt',None)

        uf.save()
        return HttpResponse('upload ok!')
    return render(request,'upload/register.html',{'uf':uf})

def display(request):
    filelist = userfile.objects.all()
    context = {'filelist':filelist}
    return render(request,"upload/filelist.html",context)

templates/Login/change-password.html
<!-- extends表明此页面继承自 baseHome.html 文件 -->
{% extends "baseHome.html" %}
{% load staticfiles %}

<!-- 写入 baseHome.html 中定义的 title -->
{% block title %}
    修改密码
{% endblock title %}

<!--加入滚动条-->
<div style="position:absolute; height:400px; overflow:auto">
</div>

{% block head %}
    <link href="//cdn.bootcss.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
{% endblock head %}

{% block style %}
    <style type="text/css">
        body{
            font-size: 16px;
        }
        .form{
            background: rgba(255,255,255,0.2);
            width: 400px;
            margin: 100px auto;
        }
        #login_form{
            display: block;
        }
        .fa{
            display: inline-block;
            top: 30px;
            left: 6px;
            position: relative;
            color: #ccc;
        }
        input[type="text"],input[type="password"]{
            padding-left: 30px;
        }
    </style>
{% endblock style %}

<!-- 写入 baseHome.html 中定义的 content -->
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <h1>修改密码</h1>

            <!--<a href = "{% url 'Login:PAGE' %}">回到主页</a>-->
            <!--<a href = "{% url 'Login:usercenter' %}">个人中心</a>-->
            <a href="{% url 'Login:editprofile' %}" class="btn btn-primary">编辑个人信息</a>
            <!--<a href = "{% url 'Login:changepassword' %}">修改密码</a>-->
            <!--<a href = "{% url 'Login:logOut' %}">登出</a>-->
            <div><br></div>
                {{ changepasswordForm.errors }}
            <form action="" method = "POST">
                {% csrf_token %}
                {{ changepasswordForm.as_p }}
                <button type="submit" class="btn btn-primary">提交</button>
                <!--<button type = "submit">提交</button>-->
            </form>
        </div>
    </div>
</div>
{% endblock content %}

templates/Login/coursedetail.html
<!-- extends表明此页面继承自 baseHome.html 文件 -->
{% extends "baseHome.html" %}
{% load staticfiles %}

<!-- 写入 baseHome.html 中定义的 title -->
{% block title %}
    课程详情
{% endblock title %}

<!--加入滚动条-->
<div style="position:absolute; height:400px; overflow:auto">
</div>

{% block head %}
    <link href="//cdn.bootcss.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
{% endblock head %}

{% block style %}
    <style type="text/css">
        body{
            font-size: 16px;
        }
        .form{
            background: rgba(255,255,255,0.2);
            width: 400px;
            margin: 100px auto;
        }
        #login_form{
            display: block;
        }
        .fa{
            display: inline-block;
            top: 30px;
            left: 6px;
            position: relative;
            color: #ccc;
        }
        input[type="text"],input[type="password"]{
            padding-left: 30px;
        }
    </style>
{% endblock style %}

<!-- 写入 baseHome.html 中定义的 content -->
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            {% if user.is_authenticated %}
                <!--<a href = "{% url 'Login:logOut' %}">登出</a>-->
                <!--
                    <div class="col-8 alert alert-success">当前用户:{{ user.username }}当前用户身份:{{ request.session.role }}</div>
                -->
                
              
                <div class="col-4 alert alert-success">课程名称：{{mycourse.courseName}}</div>
                <div class="col-4 alert alert-success">授课教师：{{mycourse.teacherName}}</div>
                {% if request.session.role == '老师' %}
                    <a href="{% url 'HomeworkPublish:Homework_Publish' mycourse.id  %}" class="btn btn-primary">发布作业</a>
                    <a href="{% url 'Login:addassistant' mycourse.id  %}" class="btn btn-primary">为此课程添加助教</a>
                    <a href="#" onclick="confirm_delete()" class="btn btn-primary">删除此课程</a>
                    <script>
                        function confirm_delete() {
                            layer.open({
                                title: "来自本网页的提示",
                                content: "确认删除此课程吗？",
                                yes: function(index, layero) {
                                    location.href="{% url 'Login:coursedelete' mycourse.id %}"
                                },
                            })
                        }
                    </script>            
                {% endif %}
                {% if request.session.role == '学生' %}
                    <a href="{% url 'Login:checkcomments' mycourse.id  %}" class="btn btn-primary">查看成绩</a>
                    <a href="#" onclick="confirm_delete()" class="btn btn-primary">退出此课程</a>
                    <script>
                        function confirm_delete() {
                            layer.open({
                                title: "来自本网页的提示",
                                content: "确认退出此课程吗？",
                                yes: function(index, layero) {
                                    location.href="{% url 'Login:courserejust' mycourse.id %}"
                                },
                            })
                        }
                    </script>           
                {% endif %}
                <div><br></div>
                <div class="col-3 alert alert-warning">参课学生：</div>
                {% for s in sc %}
                    <p style="color:rgb(14, 15, 17)" ><a href='../../persondetail?user={{s.studentName}}'>{{s.studentName}}</a></p>
                {% endfor %}
                
                <div><br></div>
                <div class="col-3 alert alert-warning">作业列表</div>
                <!-- 定义放置作业列表的div容器 -->
                <div class="container">
                    <div class="row mt-2">
                        {% for Homework in hw %}
                        
                            <!-- 卡片容器 -->
                            <div class="card h-100">
                                
                                <!-- 摘要 -->
                                <div class="card-body">
                                    <p class="card-text">作业标题：{{ Homework.Homework_title|slice:'100' }}...</p>
                                    <p class="card-text">发布时间：{{ Homework.Pub_time }}</p>
                                    <p class="card-text">截止时间：{{ Homework.deadline_date}} {{ Homework.deadline_time}}</p>
                                </div>
                                
                                <!-- 注脚 -->
                                <div class="card-footer">
                                    <a href ="{% url 'Login:homeworkdetail' Homework.id %}" class="btn btn-primary">详情</a>
                                    <!--
                                    {% if request.session.role == '学生' %}
                                        <a href ="{% url 'Login:upload' Homework.id %}" class="btn btn-primary">提交此作业</a>
                                    {% endif %}
                                    -->
                                </div>
                                <p>                                
                                
                                
                                </p>
                            
                            
                        </div>
                        {% endfor %}
                        
                        

                    </div>
                </div>
                <!--
                <p>作业列表：</p>
                {% for Homework in hw %}
                    <p>
                    作业内容：{{ Homework.Homework_text}}   发布时间：{{ Homework.Pub_time }} 截止时间：{{ Homework.deadline_date}} {{ Homework.deadline_time}}
                    <a href ="{% url 'Login:homeworkdetail' Homework.id %}">详情</a>
                    {% if request.session.role == '学生' %}
                    <a href ="{% url 'Login:upload' Homework.id %}">提交此作业</a>
                    {% endif %}
                    {% if request.session.role == '老师' %}
                    <a href ="{% url 'HomeworkPublish:Homework_delete' Homework.id %}">删除此作业</a>
                    {% endif %}

                    </p>
                {% endfor %}
                -->
                

                
                {% else %}
                <form action = "" method = "POST">
                    {% csrf_token %}
                    {{ ERROR }}
                    <div class="container">
                        <div class="form row">
                                <div class="col-md-12">
                                        <h3 style="text-align: center;">Login to your account</h3>
                                        <!-- 账号 -->
                                        <div class="form-group">
                                            <i class="fa fa-user fa-lg"></i>
                                            <input class="form-control required" type="text" placeholder="请输入用户名" name="username" autofocus="autofocus">
                                        </div>
                                        
                                        <!-- 密码 -->
                                        <div class="form-group">
                                            <i class="fa fa-lock fa-lg"></i>
                                            <input class="form-control required" type="password" placeholder="请输入密码" name="password">
                                        </div>
                                        
                                        <!-- 验证码 -->
                                        <div class="form-group">
                                            {{ loginform.VerificationCode }}
                                            {{ loginform.errors.VerificationCode }}
                                        </div>
                                                            
                                        <!-- 提交按钮 -->
                                        <div class="form-group">
                                            <button type = "submit" class = "btn btn-primary btn-block btn-success">登录</button>   
                                        </div>
                                        <div class="form-group">
                                            <a href="{% url 'Login:Register' %}" role="button" class="btn btn-link pull-right " class="img-circle" style="font-size: large;">No account?</a>
                                        </div>
                                </div>
                        </div>
                    </div>
                </form>
                {% endif %}
                <br><br><br><br>

        </div>
    </div>  
</div>
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <script type="text/javascript">
        function feedback() {
            layer.open({
                title: "来自本网页的提示",
                content: "已删除此作业",
            })
        }
        window.onload = feedback;
    </script>
    {% endfor %}                    
{% endif %}
{% endblock content %}

templates/Login/edit-profile.html
<!-- extends表明此页面继承自 baseHome.html 文件 -->
{% extends "baseHome.html" %}
{% load staticfiles %}

<!-- 写入 baseHome.html 中定义的 title -->
{% block title %}
    编辑信息
{% endblock title %}

<!--加入滚动条-->
<div style="position:absolute; height:400px; overflow:auto">
</div>

<!-- 写入 baseHome.html 中定义的 content -->
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <h1>编辑信息</h1>
            <!--<a class="nav-link" href = "{% url 'Login:PAGE' %}">回到主页</a>-->
            <!--<a class="nav-link" href="{% url 'Login:usercenter' %}">个人中心</a>-->
            <!--<a class="nav-link" href = "{% url 'Login:editprofile' %}">编辑个人信息</a>-->
            <a href="{% url 'Login:changepassword' %}" class="btn btn-primary">修改密码</a>
            <!--<a class="nav-link" href = "{% url 'Login:logOut' %}">登出</a>-->
                {{ editprofileform.errors }}
            <form action="" method = "POST">
                {% csrf_token %}
                
                <!-- 用户名 -->
                <div class="form-group col-md-4">
                    <div class="col-6 alert alert-info">用户名:</div>
                    <!--<label for="id_username">用户名:</label>-->
                    
                    <input type="text" class="form-control" name="username" value="{{USER.username}}" maxlength="150" required id="id_username">
                    <!--<span class="helptext">150个字符或者更少。仅可包含字母，数字和@/./+/-/_符号。</span>-->
                </div>
                <!--
                <p>
                    <label for="id_username">用户名：</label>
                    <input type="text" name="username" value="{{USER.username}}" maxlength="150" required id="id_username" />
                    <span class="helptext">必填。150个字符或者更少。包含字母，数字和仅有的@/./+/-/_符号。</span>
                </p>
                -->
                
                <!-- 邮箱 -->
                <div class="form-group col-md-4">
                    <div class="col-9 alert alert-info">电子邮件地址:</div>
                    <!--<label for="id_email">电子邮件地址:</label> -->
                    
                    <input type="email" class="form-control" name="email" value="{{USER.email}}" maxlength="254" id="id_email">
                </div>
                <!--
                <p>
                    <label for="id_email">电子邮件地址:</label>
                    <input type="email" name="email" value="{{USER.email}}" maxlength="254" id="id_email">
                </p>
                -->

                <div class="form-group col-md-4">
                    <div class="col-5 alert alert-info">昵称:</div>
                    <!--<label for="id_nickname">昵称:</label>-->
                     
                    <input type="text" class="form-control" name="nickname" maxlength="50" id="id_nickname" value="{{USER.normaluserform.nickname}}" />
                </div>
                <!--
                <p>
                    <label for="id_nickname">昵称:</label> 
                    <input type="text" name="nickname" maxlength="50" id="id_nickname" value="{{USER.normaluserform.nickname}}" />
                </p>
                -->
                
                <div>
                    <div><br></div>
                    <div class="col-3 alert alert-info">请选择身份:</div>
                    <!--<label for="id_Identity">身份:</label> -->
                    
                    <input type = "radio" name = "Identity" value = "学生">学生
                    <input type = "radio" name = "Identity" value = "助教">助教
                    <input type = "radio" name = "Identity" value = "老师">老师
                </div>
                <button type = "submit" class="btn btn-primary">提交</button>
            </form>
        </div>
    </div>
</div>

{% endblock content %}

templates/Login/persondetail.html
<!-- extends表明此页面继承自 baseHome.html 文件 -->
{% extends "baseHome.html" %}
{% load staticfiles %}

<!-- 写入 baseHome.html 中定义的 title -->
{% block title %}
    详细信息
{% endblock title %}

<!--加入滚动条-->
<div style="position:absolute; height:400px; overflow:auto">
</div>

<!-- 写入 baseHome.html 中定义的 content -->
{% block content %}

<div class="container">
    <div class="row">
        <div class="col-12">
            
                <div><br></div>
                <div><br></div>
                <div class="col-2 alert alert-success">用户名：{{ detail.username }}</div>
                <div class="col-3 alert alert-success">邮箱：{{ detail.email }}</div>
                <div class="col-2 alert alert-success">昵称：{{ detail.normaluserform.nickname }}</div>
                <div class="col-2 alert alert-success">身份：{{ detail.normaluserform.Identity }}</div>               
                    
                
            
        </div>
    </div>
</div>
{% endblock content %}