Login/urls.py
from django.urls import path
from . import views

app_name = 'Login'
urlpatterns = [
    path('home/', views.PAGE, name = 'PAGE'),
    #path('login/', views.logIn, name = 'logIn'),
    path('logout/', views.logOut, name = 'logOut'),
    path('register/', views.Register, name = 'Register'),
    path('addcourse/', views.addcourse, name = 'addcourse'),
    path('joincourse/', views.joincourse, name = 'joincourse'),
    path('coursedetail/<int:id>',views.coursedetail, name = 'coursedetail'),
    path('homeworkdetail/<int:id>',views.homeworkdetail, name = 'homeworkdetail'),
    path('makecomments/', views.makecomments, name = 'makecomments'),
    path('coursedelete/<int:id>',views.coursedelete, name = 'coursedelete'),
    path('courserejust/<int:id>',views.courserejust, name = 'courserejust'),
    path('addassistant/<int:id>',views.addassistant, name = 'addassistant'),
    path('upload/<int:id>/',views.homeworkdetail,name = 'upload'),
    path('user-center/', views.usercenter, name = 'usercenter'),
    path('persondetail/',views.persondetail,name='persondetail'),
    path('user-center/edit-profile', views.editprofile, name = 'editprofile'),
    path('user-center/change-password', views.changepassword, name = 'changepassword'),
    path('checkcomments/<int:id>', views.checkcomments, name = 'checkcomments'),
]

notice/urls.py
from django.urls import path
from . import views

app_name = 'notice'

urlpatterns = [
    # 通知列表
    path('list/', views.NoticeListView.as_view(), name='list'),
    # 更新通知状态
    path('update/', views.NoticeUpdateView.as_view(), name='update'),
]

projectTen/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf.urls.static import static
import projectTen.settings
import notifications.urls
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Login.urls',namespace='Login')),
    path('',include('HomeworkPublish.urls',namespace='HomeworkPublish')),
    path('captcha/', include('captcha.urls')),
    path('comment/', include('comment.urls', namespace='comment')),
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
    path('notice/', include('notice.urls', namespace='notice')),
    
]+ static (projectTen.settings.MEDIA_URL, document_root=projectTen.settings.MEDIA_ROOT)

notice/models.py
from django.db import models

# Create your models here.

notice/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.views.generic import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from Login.models import stucourse
from Login.models import course
from django.contrib.auth.models import User


class NoticeListView(LoginRequiredMixin, ListView):
    """通知列表"""
    # 上下文的名称
    context_object_name = 'notices'
    # 模板位置
    template_name = 'notice/list.html'
    # 登录重定向
    login_url = '/Login/login/'

    # 未读通知的查询集
    def get_queryset(self):
        return self.request.user.notifications.unread()
    #已读通知
    def get_context_data(self, **kwargs):
        # 获取原有的上下文
        context = super().get_context_data(**kwargs)
        # 增加新上下文
        notices_readed=self.request.user.notifications.read()
        context['readednotices'] = notices_readed
        return context

class NoticeUpdateView(View):
    """更新通知状态"""
    # 处理 get 请求
    def get(self, request):
        # 获取未读消息
        notice_id = request.GET.get('notice_id')
        # 更新单条通知
        if notice_id:
            request.user.notifications.get(id=notice_id).mark_as_read()
            return redirect('notice:list')
        # 更新全部通知
        else:
            request.user.notifications.mark_all_as_read()
            return redirect('notice:list')

templates/notice/list.html
{% extends "baseHome.html" %}
{% load staticfiles %}

{% block title %}
    通知
{% endblock title %}

<!--加入滚动条-->
<div style="position:absolute; height:400px; overflow:auto">
</div>

{% block content %}
<div class="container">
    <div class="row mt-4 ml-4">
        <a href="{% url "notice:update" %}" class="btn btn-warning" role="button">清空所有未读通知</a>
    </div>
    <br>
    <!-- 未读通知列表 -->
    <div class="col-2 alert alert-success">
        未读消息:
    </div>
    <div class="row mt-2 ml-4">
        <ul class="list-group">
            {% for notice in notices %}
                <li class="list-group-item" id="notice_link">
                    <a href="{% url "notice:update" %}?notice_id={{ notice.id }}"
                       target="_blank"
                    >
                    <span style="color: #5897fb;">
                        {{ notice.actor }}
                    </span>
                        在 <span style="color: #01a252;">{{ notice.target }}</span> {{ notice.verb }}。
                    </a>
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{ notice.timestamp|date:"Y/m/d H:i" }}
                </li>
            {% endfor %}
        </ul>
    </div>
    <!-- 已读通知列表 -->
    <div class="col-2 alert alert-success">
        已读消息:
    </div>
    <div class="row mt-2 ml-4">
        <ul class="list-group">
            {% for notice in readednotices %}
                <li class="list-group-item" id="notice_link">
                    
                    <span style="color: #5897fb;">
                        {{ notice.actor }}
                    </span>
                        在 <span style="color: #01a252;">{{ notice.target }}</span> {{ notice.verb }}。
                    </a>
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{ notice.timestamp|date:"Y/m/d H:i" }}
                </li>
            {% endfor %}
        </ul>
    </div>
</div>

<style>
    #notice_link a:link {
        color: black;
    }

    #notice_link a:visited {
        color: lightgrey;
    }
</style>
{% endblock content %}