Login/urls.py
from django.urls import path
from . import views

app_name = 'Login'
urlpatterns = [
    path('home/', views.PAGE, name = 'PAGE'),
    #path('login/', views.logIn, name = 'logIn'),
    path('logout/', views.logOut, name = 'logOut'),
    path('register/', views.Register, name = 'Register'),
    path('addcourse/', views.addcourse, name = 'addcourse'),
    path('joincourse/', views.joincourse, name = 'joincourse'),
    path('coursedetail/<int:id>',views.coursedetail, name = 'coursedetail'),
    path('homeworkdetail/<int:id>',views.homeworkdetail, name = 'homeworkdetail'),
    path('makecomments/', views.makecomments, name = 'makecomments'),
    path('coursedelete/<int:id>',views.coursedelete, name = 'coursedelete'),
    path('courserejust/<int:id>',views.courserejust, name = 'courserejust'),
    path('addassistant/<int:id>',views.addassistant, name = 'addassistant'),
    path('upload/<int:id>/',views.homeworkdetail,name = 'upload'),
    path('user-center/', views.usercenter, name = 'usercenter'),
    path('persondetail/',views.persondetail,name='persondetail'),
    path('user-center/edit-profile', views.editprofile, name = 'editprofile'),
    path('user-center/change-password', views.changepassword, name = 'changepassword'),
    path('checkcomments/<int:id>', views.checkcomments, name = 'checkcomments'),
]

projectTen/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf.urls.static import static
import projectTen.settings
import notifications.urls
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Login.urls',namespace='Login')),
    path('',include('HomeworkPublish.urls',namespace='HomeworkPublish')),
    path('captcha/', include('captcha.urls')),
    path('comment/', include('comment.urls', namespace='comment')),
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
    path('notice/', include('notice.urls', namespace='notice')),
    
]+ static (projectTen.settings.MEDIA_URL, document_root=projectTen.settings.MEDIA_ROOT)

templates/baseHome.html
<!-- 载入静态文件 -->
{% load staticfiles %}

<!DOCTYPE html>
<!-- 网站主语言 -->
<html lang="zh-cn">

<head>
    <!-- 网站采用的字符编码 -->
    <meta charset="utf-8">
    <!-- 预留网站标题的位置 -->
    <title>{% block title %}{% endblock %}</title>
    <!-- 引入bootstrap的css文件 -->
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="shortcut icon"type="image/x-icon" href="/static/images/bitbug_favicon.ico" media="screen" />
    {% block head %}{% endblock head %}

    {% block style %}{% endblock style %}

    {% block js %}{% endblock js %}
</head>

<body background="/static/images/bg.jpg" style=" background-repeat:no-repeat ;background-size:100% 100%;
background-attachment: fixed;">
    <!-- 引入导航栏 -->
    {% include 'headerHome.html' %}

    
    {% block content %}{% endblock content %}

    <!-- 引入注脚 -->
    {% include 'footer.html' %}
    
    <!-- bootstrap.js 依赖 jquery.js 和popper.js，因此在这里引入 -->
    <script src="{% static 'jquery/jquery.js' %}"></script>
    <script src="{% static 'popper/popper.js' %}"></script>    
    <!-- 引入bootstrap的js文件 -->
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <!-- 引入layer.js -->
    <script src="{% static 'layer/layer.js' %}"></script>
</body>

</html>

templates/footer.html
{% load staticfiles %}
<!-- Footer -->
<footer class="py-3 bg-dark fixed-bottom">
    <div class="container">
        <p class="m-0 text-center text-white">
            Contact us:
            <img src="{% static 'images/blank.PNG' %}" width="10" height="35">
            <a href="https://github.com/SoftwareGroupTen/demo2">
                <img src="{% static 'images/gitSign.PNG' %}" width="35" height="35">
            </a>
            <img src="{% static 'images/blank.PNG' %}" width="10" height="35">
            <a href="mailto:service@sjtu.edu.cn ">
                <img src="{% static 'images/mailSign.PNG' %}" width="35" height="35">
            </a>
            <img src="{% static 'images/blank.PNG' %}" width="10" height="35">
            <!--<a href="https://weibo.com/">
                <img src="{% static 'images/weiboSign.PNG' %}" width="35" height="35">
            </a>
            <img src="{% static 'images/blank.PNG' %}" width="10" height="35">-->
            <a href="http://localhost:8000/files/files/wx.png">
                <img src="{% static 'images/wechatSign.PNG' %}" width="35" height="35">
            </a>
        </p>
        
        <p class="m-0 text-center text-white">CopyRight &copy; SJTU SoftwareEngineering Group10</p>
    </div>
</footer>

templates/headerHome.html
{% load notifications_tags %}
{% notifications_unread as unread_count %}
{% load staticfiles %}
<!-- 定义导航栏 -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <!-- 导航栏商标 -->
        <a class="navbar-brand" href="#">
            <img src="{% static 'images/symbol.png' %}" width="28" height="28">
            Good Homework Online
        </a>
        {% if user.is_authenticated %}

            <div>
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" style="color:white" href = "{% url 'Login:PAGE' %}">主页</a>
                    </li>
    
            <!-- 如果用户已经登录，则显示用户名下拉框 -->
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" style="color:white" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <!-- 新增代码，小红点 -->
                    {% if unread_count %}
                        <svg viewBox="0 0 8 8"
                        width="8px"
                        height="8px">
                        <circle cx="4"
                        cy="4"
                        r="4"
                        fill="#ff6b6b"
                        ></circle>
                    </svg>
                {% endif %}
                {{ user.username }}
                {{ user.normaluserform.Identity }}
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <!-- 新增代码，通知计数 -->
                        <a class="dropdown-item" href="../../notice/list">通知
                            {% if unread_count %}
                            <span class="badge badge-danger">{{ unread_count }}</span>
                            {% endif %}
                        </a>
                <a class="dropdown-item" href="{% url 'Login:usercenter' %} ">个人中心</a>
                <a class="dropdown-item" href="#" onclick="confirmLogout()">退出登录</a>
                </div>
            </li>

            </div>
            
            
        {% else %}
            <!-- 导航入口 -->
            <div>
                <ul class="navbar-nav">
                    <!-- 条目 -->
                    <li class="nav-item">
                        <a class="nav-link" href ="{% url 'Login:PAGE' %}"> <font size="2">请先登录或注册 </font> </a>
                    </li>
                </ul>
            </>
        {% endif %}
  
    </div>
</nav>

<script>
    // 退出登录的函数
    function confirmLogout() {
        // 调用layer弹窗组件
        layer.open({
            // 弹窗标题
            title: "退出登录",
            // 正文
            content: "确认退出当前账号吗？",
            // 点击确定按钮后调用的回调函数
            yes: function(index, layero) {
                // 指定应当前往的 url
                location.href="{% url 'Login:logOut' %}"
            },
        })
    }
</script>